//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetAnotherSudokuPlayer.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YetAnotherSudokuPlayer.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.1...4.5
        ///.7.....1.
        ///.3..7..9.
        ///..28476..
        ///....2....
        ///..63517..
        ///.4..3..5.
        ///.2.....6.
        ///7.5...8.3.
        /// </summary>
        internal static string hard {
            get {
                return ResourceManager.GetString("hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..83.41..
        ///..3...2..
        ///12.....63
        ///5..7.8..1
        ///.........
        ///8..4.3..5
        ///43.....19
        ///..1...7..
        ///..69.18...
        /// </summary>
        internal static string medium {
            get {
                return ResourceManager.GetString("medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 564.871238.732.45623165.7899184325676.519823434276.8914538769127.621934512954367..
        /// </summary>
        internal static string test1 {
            get {
                return ResourceManager.GetString("test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 987321.64654.8723..216548971984.26757.519834243276591.876219453219.437865438761.9.
        /// </summary>
        internal static string test2 {
            get {
                return ResourceManager.GetString("test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .3.5.498.
        ///.9..3....
        ///46.8.....
        ///.7..1843.
        ///8.9.4..6.
        ///..3......
        ///.2...38..
        ///6...2...3
        ///.5.7.6..9
        ///.
        /// </summary>
        internal static string test3 {
            get {
                return ResourceManager.GetString("test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .5.481.2.
        ///3.8.6.4.9
        ///.4.....5.
        ///1...2...6
        ///68.1.7.94
        ///7...9...5
        ///.3.....8.
        ///8.1.3.5.2
        ///.7.248.6.
        ///.
        /// </summary>
        internal static string veryeasy {
            get {
                return ResourceManager.GetString("veryeasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...4.5...
        ///.3.719.4.
        ///..9...1..
        ///19..6..25
        ///.6.5.7.1.
        ///35..4..79
        ///..5...7..
        ///.4.658.9.
        ///...9.2....
        /// </summary>
        internal static string veryhard {
            get {
                return ResourceManager.GetString("veryhard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....2....
        ///.8.5.7.1.
        ///..46.13..
        ///.178.352.
        ///3.......9
        ///.261.973.
        ///..19.62..
        ///.4.2.5.7.
        ///....7....
        ///.
        /// </summary>
        internal static string veryhard2 {
            get {
                return ResourceManager.GetString("veryhard2", resourceCulture);
            }
        }
    }
}
